# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/clojure:1.11.1-node
    working_directory: ~/repo
    # resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "package-lock.json" }}
            # fallbacks to using the latest cache if no exact match is found
            - v1-dependencies-{{ checksum "deps.edn" }}-
            - v1-dependencies-

      - run:
          name: Build assets
          command: |
            script/build/assets
            
      - run:
          name: Create jars
          command: |
            script/build/jars
            mkdir -p /tmp/workspace/release
            DIR=/tmp/workspace/release script/ci/release
            
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - release

      - store_artifacts:
          path: /tmp/workspace/release
          destination: release
          
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ~/.npm
          key: v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "package-lock.json" }}
  
  docker:
    docker: 
      - image: docker:17.05.0-ce-git

    working_directory: ~/repo
    steps:      
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Create Docker image
          command: |
            DIR=/tmp/workspace/release script/build/docker


workflows:
  version: 2
  ci:
    jobs:
      # - short-if-irrelevant
      # - jvm:
      #     requires:
      #        - short-if-irrelevant
      
      - deploy
        # filters:
        #   branches:
        #     only: master
        # requires:
        #   - jvm
      - docker:
          requires:
            - deploy

