# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/clojure:1.11.1-node
    working_directory: ~/repo
    # resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "package-lock.json" }}
            # fallbacks to using the latest cache if no exact match is found
            - v1-dependencies-{{ checksum "deps.edn" }}-
            - v1-dependencies-

      - run:
          name: Build assets
          command: |
            script/build/assets
            
      - run:
          name: Create uberjar
          command: |
            script/build/uberjar
            mkdir -p /tmp/release
            DIR=/tmp/release script/ci/release

      - store_artifacts:
          path: /tmp/release
          destination: release
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
            - ~/.npm
          key: v1-dependencies-{{ checksum "deps.edn" }}-{{ checksum "package-lock.json" }}


workflows:
  version: 2
  ci:
    jobs:
      # - short-if-irrelevant
      # - jvm:
      #     requires:
      #        - short-if-irrelevant
      - deploy
        # filters:
        #   branches:
        #     only: master
        # requires:
        #   - jvm

